name: bytezap
version: 1.1.0
synopsis: Bytestring builder with zero intermediate allocation
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Data, Serialization, Generics
license: MIT
license-file: LICENSE

github: raehik/bytezap
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

tested-with:
- GHC == 9.6.4

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

dependencies:
- base >= 4.18.0.0 && < 4.20 # blaze it
- primitive >= 0.8.0.0 && < 0.10.0.0
- bytestring >= 0.11.5.3 && < 0.13.0.0
- text >= 2.0.2 && < 2.2

library:
  source-dirs: src
  c-sources:
  - cbits/aligned-static-hs-data.c
